# Generated by Django 4.0.6 on 2022-08-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('Email', models.EmailField(max_length=245)),
                ('Debt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.IntegerField()),
                ('AmountPaid', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('phone_num', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Active', max_length=50)),
                ('Student_id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False)),
            ],
        ),
    ]
