# Generated by Django 4.0.6 on 2022-07-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100000000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(max_length=1000)),
                ('party', models.CharField(max_length=10000000)),
            ],
        ),
    ]
