# Generated by Django 4.0.6 on 2022-07-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='student',
            new_name='studentId',
        ),
    ]
