# Generated by Django 4.0.6 on 2022-08-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0004_post_profile_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='std_id',
            field=models.IntegerField(default=1234),
        ),
        migrations.AddField(
            model_name='post',
            name='std_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='contenders',
            field=models.ManyToManyField(related_name='debtor', to='contend.contender'),
        ),
    ]
