# Generated by Django 4.0.6 on 2022-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0005_post_std_id_post_std_name_contender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contender',
            name='contender_name',
            field=models.ManyToManyField(related_name='debtor_id', to='contend.post'),
        ),
    ]
