# Generated by Django 4.0.6 on 2022-08-02 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0006_contender_contender_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contender',
            name='contender_name',
        ),
        migrations.AddField(
            model_name='contender',
            name='contender_name',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='contend.post'),
        ),
    ]
