# Generated by Django 4.0.6 on 2022-08-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0007_remove_contender_contender_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='contender_name',
            field=models.OneToOneField(default='me', on_delete=django.db.models.deletion.CASCADE, to='contend.post'),
        ),
    ]
