# Generated by Django 4.0.6 on 2022-08-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0008_alter_contender_contender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='std_name',
            field=models.CharField(default='me', max_length=200),
        ),
    ]
