# Generated by Django 4.0.6 on 2022-08-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0009_alter_post_std_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='contender_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='std_name',
            field=models.CharField(default='debtor', max_length=200),
        ),
    ]
