# Generated by Django 4.0.6 on 2022-08-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0010_alter_contender_contender_name_alter_post_std_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contenders',
            field=models.ManyToManyField(blank=True, related_name='debtor', to='contend.contender'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('msg_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='contend.profile')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to='contend.profile')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
