# Generated by Django 4.0.6 on 2022-08-03 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contend', '0011_alter_profile_contenders_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contender_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.post')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_name', models.CharField(max_length=300)),
                ('sch_email', models.EmailField(max_length=254)),
                ('sch_wbsite', models.URLField()),
                ('sch_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('contenders', models.ManyToManyField(blank=True, related_name='debtor_profile', to='contend.contenderprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contenders',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contender',
        ),
        migrations.AddField(
            model_name='contenderprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contend.schoolprofile'),
        ),
        migrations.AddField(
            model_name='contenderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='contend.schoolprofile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to='contend.contenderprofile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
