# Generated by Django 4.0.6 on 2022-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contend', '0012_contenderprofile_schoolprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='contenders',
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msg_sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='message',
            name='seen',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='default', max_length=10000000),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='default', max_length=1000),
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default='default', max_length=100000000),
        ),
        migrations.DeleteModel(
            name='ContenderProfile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
