# Generated by Django 4.0.6 on 2022-08-09 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.schoolemail'),
        ),
    ]
