# Generated by Django 4.0.6 on 2022-08-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_schoolmodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolmodel',
            old_name='email',
            new_name='emails',
        ),
    ]
